import crypto from 'node:crypto';

const MERCHANT_ID = import.meta.env.CRYPTOMUS_MERCHANT_ID;
const PAYMENT_KEY = import.meta.env.CRYPTOMUS_PAYMENT_KEY;

interface CreatePaymentParams {
    amount: string;
    currency: string;
    order_id: string;
    url_return?: string;
    url_success?: string;
    url_callback?: string;
    is_test?: boolean;
}

export class CryptomusService {
    private static generateSignature(data: any): string {
        const jsonStr = JSON.stringify(data);
        const base64 = Buffer.from(jsonStr).toString('base64');
        return crypto
            .createHash('md5')
            .update(base64 + PAYMENT_KEY)
            .digest('hex');
    }

    static async createPayment(params: CreatePaymentParams) {
        if (!MERCHANT_ID || !PAYMENT_KEY) {
            throw new Error('Cryptomus credentials not found in environment variables');
        }

        const payload = {
            ...params,
            merchant: MERCHANT_ID
        };

        const signature = this.generateSignature(payload);

        const response = await fetch('https://api.cryptomus.com/v1/payment', {
            method: 'POST',
            headers: {
                'merchant': MERCHANT_ID,
                'sign': signature,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(payload)
        });

        const data = await response.json();

        if (data.state !== 0) {
            console.error('Cryptomus Error:', data);
            throw new Error(data.message || 'Failed to create Cryptomus payment');
        }

        return data.result;
    }

    static verifySignature(payload: any, sign: string): boolean {
        if (!PAYMENT_KEY) return false;

        // For callback, the signature is generated by removing 'sign' and hashing the rest
        const { sign: _, ...data } = payload;
        const jsonStr = JSON.stringify(data).replace(/\//g, '\\/'); // Cryptomus callbacks escape slashes
        const base64 = Buffer.from(jsonStr).toString('base64');
        const expectedSign = crypto
            .createHash('md5')
            .update(base64 + PAYMENT_KEY)
            .digest('hex');

        return expectedSign === sign;
    }
}
